# Generated by Django 4.2.20 on 2025-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_task_taskmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMoel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
