# Generated by Django 4.2.20 on 2025-03-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_taskmoel_delete_taskmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskMoel',
            new_name='TaskModel',
        ),
    ]
