# Generated by Django 4.2.20 on 2025-03-15 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_taskmoel_taskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
