# Generated by Django 4.2.13 on 2025-03-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_taskmodel_id_taskmodel__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
