# Generated by Django 4.2.13 on 2025-03-15 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_taskmodel__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
