# Generated by Django 4.2.13 on 2025-03-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_taskmodel__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='_id',
            new_name='id',
        ),
    ]
