# Generated by Django 4.2.13 on 2025-03-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename__id_taskmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='id',
            new_name='_id',
        ),
    ]
