# Generated by Django 4.2.13 on 2025-03-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename__id_taskmodel_sino'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
